

//演示抛出异常的流程
	class Test{
		void run(int[] arr, int index){
			System.out.println(arr[index]);
		}
	}
public class ExceptionDemo {
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int[] arr = new int[5];
		int[] array = null;
		
		//arr[5] = 134;
		//array[0] = 123;
		Test test = new Test();
		test.run();
		
		System.out.println("==================");
	}

}
